---
#  https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  amd64: "ghcr.io/home-assistant/amd64-base:3.20"

labels:
  org.opencontainers.image.title: "SBFspot for Home Assistant"
  org.opencontainers.image.description: "SBFspot for new add-ons."
  org.opencontainers.image.source: "https://github.com/habuild"
  org.opencontainers.image.licenses: "Apache License 2.0"
codenotary:
  base_image: notary@home-assistant.io
args:
  TEMPIO_VERSION: "2021.09.0"
